"""Specialized Python functions exposed to the agent through @tool.

The decorator in tool.py registers callable metadata and provider schemas.
Context is supplied internally, not generated by an LLM.
"""
from datetime import datetime, timezone
from uuid import uuid4
from .tool import tool
from .context import Context
from .model import Quality, Result, Candidate, Verification, Issue, Evidence, FIELDS, effective_field
from .demo import demo_extraction
from .errors import AnalysisError
from .providers import safe_medicine_fragment


def patient_summary(result):
    sentences = []
    for i, med in enumerate(result.medications):
        name = effective_field(result, med, 'medicine_name')
        text = f'Medicine {i+1}: {name.value if name.status == "readable" else "Unclear — please verify with your doctor or pharmacist"}. '
        for field in FIELDS[1:]:
            value = effective_field(result, med, field)
            if value.status == 'readable' and value.value:
                text += f'{field.replace("_", " ")}: {value.value}. '
        sentences.append(text)
    return '\n'.join(sentences)


@tool()
def analyze_prescription_image(context: Context):
    """Screen image resolution, brightness and sharpness. No page-edge or perspective claims."""
    metrics = context.metrics or context.input.metrics
    warnings = []
    if min(metrics.width, metrics.height) < 600:
        warnings.append('The image resolution is low.')
    if metrics.brightness < 60:
        warnings.append('The image may be too dark.')
    if metrics.brightness > 245:
        warnings.append('The image may be overexposed.')
    if metrics.sharpness < 25:
        warnings.append('The image may be blurry.')
    context.quality = Quality(quality_score=max(.1, 1-len(warnings)*.23), is_readable=not warnings,
        blur_detected=metrics.sharpness < 25,
        lighting_quality='dark' if metrics.brightness < 60 else 'bright' if metrics.brightness > 245 else 'good',
        recommendation='retake' if warnings else 'proceed', warnings=warnings,
        method='Basic pixel screening; page cropping and perspective need visual review.')
    if warnings and not context.input.allowPoor:
        raise AnalysisError('quality_retake', 'quality')


@tool(requires=('analyze_prescription_image',))
async def extract_prescription_text(context: Context):
    """Extract the prescription image using structured Gemini vision output; preserve uncertain fields."""
    context.extraction = (demo_extraction(context.input.sample) if context.input.sample else
                          await context.providers.extract(context.image or context.input.image))
    if not context.extraction.is_prescription:
        raise AnalysisError('not_prescription', 'handwriting')
    if not context.extraction.medications:
        raise AnalysisError('unreadable', 'handwriting')


@tool(requires=('extract_prescription_text',))
def structure_prescription(context: Context):
    """Create a structured prescription from extracted fields without inventing missing information."""
    context.result = Result(**context.extraction.model_dump(), prescription_id=str(uuid4()),
        created_at=datetime.now(timezone.utc).isoformat(), mode='demo' if context.input.sample else 'live',
        quality=context.quality,
        source_label='Synthetic sample — illustrative extraction' if context.input.sample else 'AI transcription — not clinically validated')


@tool(requires=('structure_prescription',))
async def identify_medicine(context: Context):
    """Find local or RxNorm medicine candidates; candidates do not prove the handwriting."""
    for med in context.result.medications:
        reading = med.fields['medicine_name']
        if reading.status == 'crossed_out':
            continue
        name = reading.value or reading.raw
        if context.input.sample:
            names = ['Panadol (paracetamol)'] if name == 'Panadol' else ['Cetirizine'] if name == 'Cetirizine' else ['Amlodipine', 'Amiloride']
            found = {'candidates': [{'name': n, 'source': 'Illustrative demo catalog — not a live database'} for n in names],
                     'status': 'multiple' if len(names) > 1 else 'matched'}
        else:
            name = safe_medicine_fragment(reading.value)
            if not name:
                med.candidates, med.catalog_status = [], 'unmatched'
                continue
            candidates = context.catalog.lookup(name)
            found = ({'candidates': candidates, 'status': 'multiple' if len(candidates) > 1 else 'matched'}
                     if candidates else await context.providers.lookup_rxnorm(name))
        med.candidates = [Candidate.model_validate(c) for c in found['candidates']]
        med.catalog_status = found['status']


@tool(requires=('identify_medicine',))
async def search_medicine_web(context: Context):
    """Retrieve optional Tavily medicine-name evidence. Never overwrite the extracted name or confidence."""
    searches = 0
    for med in context.result.medications:
        name = med.fields['medicine_name']
        if (context.input.sample or name.status == 'crossed_out' or searches >= 3 or
                name.status == 'readable' and any(c.match_method == 'exact_name' for c in med.candidates)):
            med.web_status, med.web_evidence = 'skipped', []
            continue
        found = await context.providers.search_medicine(name.value)
        med.web_status = found['status']
        med.web_evidence = [Evidence.model_validate(e) for e in found['evidence']]
        if found['status'] not in ('skipped', 'not_configured'):
            searches += 1


@tool(requires=('identify_medicine', 'search_medicine_web'))
def verify_medicine(context: Context):
    """Check exact reference identity. Unverified retail data cannot establish a verified medicine."""
    for med in context.result.medications:
        name = med.fields['medicine_name'].value or ''
        candidate = med.candidates[0] if len(med.candidates) == 1 else None
        med.catalog_verification = Verification(
            verified=bool(candidate and candidate.review_status != 'unverified' and candidate.name.lower() == name.lower()),
            reason='Catalog recognition does not verify handwriting or infer strength/form.',
            source=med.candidates[0].source if med.candidates else 'Catalog unavailable')


@tool(requires=('verify_medicine',))
def check_prescription_consistency(context: Context):
    """Flag missing, uncertain, crossed-out and duplicate fields without treatment advice."""
    seen, issues = set(), []
    for med in context.result.medications:
        for name in FIELDS:
            reading = med.fields[name]
            if reading.status != 'readable':
                message = ('Possibly crossed out — do not rely on this entry.' if reading.status == 'crossed_out' else
                           f'{name.replace("_", " ")} is {"not written or not readable" if reading.status == "missing" else "unclear"}; verify if needed.')
                issues.append(Issue(medication_id=med.id, field=name, message=message))
        name = (med.fields['medicine_name'].value or '').lower()
        if name and name in seen:
            issues.append(Issue(medication_id=med.id, field='medicine_name', message='Repeated name. Check both original entries.'))
        if name:
            seen.add(name)
    context.result.issues = issues


@tool(requires=('check_prescription_consistency',))
def generate_patient_summary(context: Context):
    """Produce a faithful plain-language summary, explicitly preserving unknown readings."""
    context.result.summary = patient_summary(context.result)
