import { z } from 'zod';
export const fields = ['medicine_name','strength','form','dose','frequency','timing','duration','instructions'] as const;
export type FieldName = typeof fields[number];
export const fieldSchema = z.object({value:z.string().max(500).nullable(),raw:z.string().max(500),confidence:z.number().min(0).max(1),status:z.enum(['readable','uncertain','missing','crossed_out'])});
export type Field = z.infer<typeof fieldSchema>;
export const medicationSchema = z.object({id:z.string().max(80),raw_text:z.string().max(2000),region:z.tuple([z.number().min(0).max(1),z.number().min(0).max(1),z.number().min(0).max(1),z.number().min(0).max(1)]).nullable(),fields:z.object(Object.fromEntries(fields.map(f=>[f,fieldSchema])) as Record<FieldName,typeof fieldSchema>),candidates:z.array(z.object({name:z.string().max(200),source:z.string().max(200),id:z.string().max(80).optional(),url:z.string().url().max(2000).optional(),manufacturer:z.string().max(300).optional(),pack:z.string().max(300).optional(),country:z.string().max(50).optional(),review_status:z.enum(["unverified","verified_reference"]).optional(),match_method:z.enum(["exact_name","similar_spelling"]).optional()})).max(8).default([]),web_status:z.enum(["matched","unmatched","unavailable","not_configured","skipped","quota"]).optional(),web_evidence:z.array(z.object({title:z.string().max(250),url:z.string().url().max(2000),source_type:z.enum(["regulator","manufacturer","retailer"]),excerpt:z.string().max(500),retrieved_at:z.string().max(100)})).max(5).optional(),catalog_verification:z.object({verified:z.boolean(),reason:z.string().max(500),source:z.string().max(200)}).optional(),catalog_status:z.enum(['matched','multiple','unavailable','unmatched']).default('unavailable'),verification_status:z.enum(['pending','confirmed','unresolved']).default('pending')});
export type Medication=z.infer<typeof medicationSchema>;
export const extractionSchema=z.object({is_prescription:z.boolean(),patient_name:z.string().max(200).nullable(),doctor_name:z.string().max(200).nullable(),date:z.string().max(100).nullable(),medications:z.array(medicationSchema).max(20),additional_instructions:z.array(fieldSchema).max(20),follow_up:fieldSchema.nullable()});
export type Extraction=z.infer<typeof extractionSchema>;
export type Quality={quality_score:number;is_readable:boolean;blur_detected:boolean;lighting_quality:string;perspective_issue:boolean|null;cropped_content:boolean|null;recommendation:'proceed'|'retake';warnings:string[];method:string};
export type Correction={medication_id:string;field:FieldName;ai_value:string|null;user_value:string;created_at:string;source:'user';confirmed:boolean};
export type Result=Extraction & {prescription_id:string;created_at:string;mode:'demo'|'live';quality:Quality;issues:{medication_id:string;field:string;message:string}[];user_corrections:Correction[];trace:{tool:string;duration_ms:number;status:string}[];summary:string;source_label:string};
export function normalizeExtraction(input:unknown):Extraction { const r=extractionSchema.parse(input); const ids=new Set<string>();for(const m of r.medications){if(ids.has(m.id))throw new Error('duplicate_id');ids.add(m.id);if(m.region&&(m.region[2]<=m.region[0]||m.region[3]<=m.region[1]))m.region=null;m.verification_status='pending';m.candidates=[];m.catalog_status='unavailable'; for(const f of fields){const v=m.fields[f];if(f==='strength'&&v.status!=='crossed_out'&&/\b(?:mg|mcg|µg|g|ml|iu)\b|%/i.test(v.raw||v.value||'')&&!/\d/.test(v.raw||v.value||'')){v.value=null;v.status='uncertain';v.confidence=Math.min(v.confidence,.5);}if(!v.value||v.confidence<.85||v.status!=='readable'){v.status=v.status==='crossed_out'?'crossed_out':v.value||v.status==='uncertain'||v.raw.trim()?'uncertain':'missing';}}}return r; }
export function effectiveField(r:Result,m:Medication,f:FieldName):Field {const c=[...r.user_corrections].reverse().find(c=>c.medication_id===m.id&&c.field===f);return c?{value:c.user_value||null,raw:m.fields[f].raw,confidence:c.confirmed?1:0,status:c.user_value?(c.confirmed?'readable':'uncertain'):'missing'}:m.fields[f];}
export function exportText(r:Result){return ['AI-assisted transcription — verify against the original prescription.',r.mode==='demo'?'DEMO SAMPLE — not a personal prescription.':'',...r.medications.flatMap((m,i)=>[`\nMedicine ${i+1} (${m.verification_status==='confirmed'?'user confirmed':'not fully confirmed'})`,...fields.flatMap(f=>{const v=effectiveField(r,m,f);return v.status==='readable'&&v.value?[`${f.replaceAll('_',' ')}: ${v.value}`]:[];})]),'\nUnclear and crossed-out fields are omitted. This is a transcription, not treatment advice.'].join('\n');}
